name: maveshi
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^10.1.0
  responsive_framework: ^0.2.0
  hawk_fab_menu: ^1.1.2
  provider: ^6.0.3
  firebase_core: ^1.14.1
  firebase_analytics: ^9.1.5
  cloud_firestore: ^3.1.12
  firebase_storage: ^10.2.12
  firebase_auth: ^3.3.14
  google_sign_in: ^5.3.0
  json_annotation: ^4.5.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  flutter_easyloading: ^3.0.5
  get_it: ^7.2.0
  syncfusion_flutter_charts: ^20.1.59

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.0.0
  build_runner: ^2.1.11 # flutter pub run build_runner build
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
