// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE3c_R3EMFpV4eBIiEW-wR2aXEntcN89c',
    appId: '1:936695083325:android:fbc38f92fed3800560d554',
    messagingSenderId: '936695083325',
    projectId: 'maveshi-app',
    storageBucket: 'maveshi-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4BT7iNhAoQsUNJCzCp1hIaF3bPnHNDXY',
    appId: '1:936695083325:ios:a406c8d00257460460d554',
    messagingSenderId: '936695083325',
    projectId: 'maveshi-app',
    storageBucket: 'maveshi-app.appspot.com',
    iosClientId: '936695083325-m6b15pq2bbj7c766hj32b54m5l4r59hq.apps.googleusercontent.com',
    iosBundleId: 'dev.ahmadkhan.maveshi',
  );
}
